FROM node:18-alpine

# Set the working directory
WORKDIR /Application-Test/frontend

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install project dependencies
RUN npm install

COPY frontend/ .

EXPOSE 4200
 
CMD ["npm", "start"]