version: '3'
services:
  # Laravel backend service
  laravel:
    build:
      context: ./backend
      dockerfile: C:/final/Application-Test/backend/Dockerfile #absolute path expected here
    image: backend
    container_name: laravel-container
    restart: unless-stopped
    working_dir: /Application-Test/backend
    ports:
      - 8000:8000

  # Angular frontend service
  angular:
    build:
      context: ./frontend
      dockerfile: C:/final/Application-Test/frontend/Dockerfile #absolute path expected here
    image: frontend
    container_name: angular-container
    restart: unless-stopped
    working_dir: frontend
    ports:
      - 4200:4200
    depends_on:
      - laravel
