version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  angular:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "4200:4200"